name: TellCo_Data_Analysis
on: 
  push:
    branches:
    - main
jobs:
  run:
    runs-on: ubuntu-latest 
    container: docker://dvcorg/cml-py3:latest
    steps:
    - uses: actions/checkout@v2
    - name: cml_run
